### ISSUE TITLE
您好，您这个项目打不开，缺少UserApi这个类

### ISSUE THREAD

**Issue by summerzh** [ImKarl/JianshuApp#1]
今天看到了您这个项目，编译后发现缺少UserApi这个类，您有时间可以看看吗。

**Comment by imkarl** [comment]
因为接口是抓包简书的，如果直接公开接口并不合适。目前还没想好怎么合理的开放接口部分

**Comment by summerzh** [comment]
能理解。看您这个项目完成度很高，我想好好学习下，能否单独发我邮箱，我保证不会用于传播，只是用于自己学习。希望您能答应我。谢谢，我邮箱是teng13114@qq.com

发自我的 iPhone

**Comment by imkarl** [comment]
可以的，项目的本意就是要共享开源。
我整理下，发你邮箱

**Comment by zxldsg** [comment]
你好，你这个项目缺少了api的包吧

**Comment by imkarl** [comment]
可以考虑在 jianshuapp/modellayer/repository 模块下提供模拟数据。
过段时间会考虑将 api 部分的代码更新出来

**Comment by liuyueyi** [comment]
不要直接把类删掉啊，里面的数据可以mock；
缺少类，连怎么补都不好搞

**Comment by imkarl** [comment]
这个可以的，，
最近一直在忙其他事情，没时间来处理api部分
还有很多界面没做仿写完。可能要年后才会补全了

mock的数据 今天晚点加上

**Comment by imkarl** [comment]
mock 数据已经加上，可以在 `/modellayer/remote/api/mock`修改模拟的数据
